import { closeCashAction, openCashAction } from "@/app/system-actions";
import { query } from "@/lib/db";
import { formatDateTime, formatMoney } from "@/lib/format";
import { requireRole } from "@/lib/auth";

export default async function CashPage({ searchParams }: { searchParams: Promise<{ erro?: string }> }) {
  await requireRole(["ADMIN", "MANAGER", "CASHIER"]);
  const { erro } = await searchParams;
  const current = await query<{ id:number; opening_amount_cents:number; opened_at:string; opened_by_name:string }>(`SELECT cs.id,cs.opening_amount_cents,cs.opened_at,u.name AS opened_by_name FROM cash_sessions cs JOIN users u ON u.id=cs.opened_by WHERE cs.status='OPEN' LIMIT 1`);
  const cash = current.rows[0];
  const totals = cash ? await query<{ method:string; total:string }>(`SELECT p.method,COALESCE(SUM(p.amount_cents),0)::text AS total FROM payments p JOIN sales s ON s.id=p.sale_id WHERE s.cash_session_id=$1 AND s.status='COMPLETED' GROUP BY p.method`,[cash.id]) : {rows:[]};
  const sales = cash ? await query<{ id:number; command_number:number; total_cents:number; created_at:string }>(`SELECT s.id,c.command_number,s.total_cents,s.created_at FROM sales s JOIN commands c ON c.id=s.command_id WHERE s.cash_session_id=$1 AND s.status='COMPLETED' ORDER BY s.created_at DESC LIMIT 20`,[cash.id]) : {rows:[]};
  const map=Object.fromEntries(totals.rows.map(t=>[t.method,Number(t.total)])); const salesTotal=Object.values(map).reduce((a,b)=>a+b,0);
  return <><div className="page-head"><div><p className="eyebrow">Financeiro</p><h2>Caixa diário</h2><p>Abra o caixa antes de finalizar a primeira venda.</p></div>{cash&&<span className="badge badge-green">Caixa aberto</span>}</div>{erro&&<div className="alert alert-error">{erro}</div>}
    {!cash?<section className="card" style={{maxWidth:560}}><h3>Abrir caixa</h3><form action={openCashAction} className="form-stack"><div className="field"><label>Valor inicial (R$)</label><input className="input" name="openingAmount" type="number" min="0" step="0.01" defaultValue="0" required/></div><button className="btn btn-primary" type="submit">Abrir caixa do dia</button></form></section>:<>
      <section className="grid grid-4"><div className="card stat"><span className="stat-label">Valor inicial</span><strong className="stat-value">{formatMoney(cash.opening_amount_cents)}</strong><span className="stat-meta">{cash.opened_by_name} · {formatDateTime(cash.opened_at)}</span></div><div className="card stat"><span className="stat-label">Vendas no caixa</span><strong className="stat-value">{formatMoney(salesTotal)}</strong><span className="stat-meta">total recebido</span></div><div className="card stat"><span className="stat-label">Dinheiro</span><strong className="stat-value">{formatMoney(map.CASH||0)}</strong><span className="stat-meta">sem descontar trocos</span></div><div className="card stat"><span className="stat-label">Pix + cartões</span><strong className="stat-value">{formatMoney((map.PIX||0)+(map.DEBIT||0)+(map.CREDIT||0))}</strong><span className="stat-meta">pagamentos eletrônicos</span></div></section>
      <div className="grid grid-2" style={{marginTop:22}}><section className="card"><h3>Vendas recentes</h3>{sales.rows.length===0?<div className="empty">Nenhuma venda neste caixa.</div>:<div className="table-wrap"><table><thead><tr><th>Venda</th><th>Comanda</th><th>Horário</th><th>Total</th></tr></thead><tbody>{sales.rows.map(s=><tr key={s.id}><td>#{s.id}</td><td>#{s.command_number}</td><td>{formatDateTime(s.created_at)}</td><td className="money">{formatMoney(s.total_cents)}</td></tr>)}</tbody></table></div>}</section>
      <section className="card"><h3>Fechar caixa</h3><p style={{color:"var(--muted)",fontSize:13}}>Informe o valor contado em dinheiro. A conferência completa será aberta para impressão.</p><form action={closeCashAction} target="_blank" className="form-stack"><input type="hidden" name="cashId" value={cash.id}/><div className="field"><label>Valor contado em dinheiro (R$)</label><input className="input" name="closingAmount" type="number" min="0" step="0.01" required/></div><div className="field"><label>Observações</label><textarea className="textarea" name="notes" rows={3}/></div><div className="field"><label>Formato</label><select className="select" name="format" defaultValue="a4"><option value="80">Térmica 80 mm</option><option value="58">Térmica 58 mm</option><option value="a4">Folha A4</option></select></div><button className="btn btn-dark" type="submit">Fechar e imprimir relatório</button></form></section></div>
    </>}
  </>;
}
