import { notFound } from "next/navigation";
import { PrintActions } from "@/components/print-actions";
import { BrandLogo } from "@/components/brand-logo";
import { requireRole } from "@/lib/auth";
import { query } from "@/lib/db";
import { formatDateTime, formatMoney } from "@/lib/format";

export const dynamic = "force-dynamic";
export default async function CashPrintPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{formato?:string}>}){
  await requireRole(["ADMIN","MANAGER"]); const cashId=Number((await params).id); const format=(await searchParams).formato||"a4"; const cash=await query<{id:number;opening_amount_cents:number;closing_amount_cents:number;expected_amount_cents:number;opened_at:string;closed_at:string;opened_by_name:string;closed_by_name:string;notes:string|null}>(`SELECT cs.id,cs.opening_amount_cents,cs.closing_amount_cents,cs.expected_amount_cents,cs.opened_at,cs.closed_at,uo.name AS opened_by_name,uc.name AS closed_by_name,cs.notes FROM cash_sessions cs JOIN users uo ON uo.id=cs.opened_by LEFT JOIN users uc ON uc.id=cs.closed_by WHERE cs.id=$1`,[cashId]); if(!cash.rows[0])notFound(); const data=cash.rows[0];
  const [payments,sales]=await Promise.all([query<{method:string;total:string}>(`SELECT p.method,SUM(p.amount_cents)::text AS total FROM payments p JOIN sales s ON s.id=p.sale_id WHERE s.cash_session_id=$1 AND s.status='COMPLETED' GROUP BY p.method`,[cashId]),query<{count:string;total:string}>(`SELECT COUNT(*)::text AS count,COALESCE(SUM(total_cents),0)::text AS total FROM sales WHERE cash_session_id=$1 AND status='COMPLETED'`,[cashId])]); const map=Object.fromEntries(payments.rows.map(p=>[p.method,Number(p.total)])); const methods:Record<string,string>={CASH:"Dinheiro das vendas",PIX:"PIX",DEBIT:"Cartão de débito",CREDIT:"Cartão de crédito",STAFF_VOUCHER:"Vale funcionário",STORE_CREDIT:"Crédito em loja"}; const paymentsTotal=Object.values(map).reduce((sum,value)=>sum+value,0);
  return <main className={`print-page ${format==="80"?"receipt-80":format==="58"?"receipt-58":""}`}><PrintActions/><header className="print-title"><BrandLogo className="print-logo"/><h1>O Pub do Bairro</h1><strong>FECHAMENTO DE CAIXA #{data.id}</strong></header><div className="divider"/><p><strong>Abertura:</strong> {formatDateTime(data.opened_at)} — {data.opened_by_name}<br/><strong>Fechamento:</strong> {data.closed_at?formatDateTime(data.closed_at):"Ainda aberto"} — {data.closed_by_name||"—"}</p><div className="divider"/><div className="totals"><div className="total-row"><span>Fundo de caixa (não é venda)</span><strong>{formatMoney(data.opening_amount_cents)}</strong></div><div className="total-row"><span>Quantidade de vendas</span><strong>{sales.rows[0]?.count||0}</strong></div><div className="total-row"><span>Total vendido</span><strong>{formatMoney(sales.rows[0]?.total||0)}</strong></div></div><div className="divider"/><strong>Vendas por forma de pagamento</strong>{Object.entries(methods).map(([key,label])=><div className="total-row" key={key} style={{marginTop:8}}><span>{label}</span><span>{formatMoney(map[key]||0)}</span></div>)}<div className="total-row grand" style={{marginTop:8}}><span>Total das formas</span><span>{formatMoney(paymentsTotal)}</span></div><div className="divider"/><strong>Conferência do dinheiro físico</strong><div className="totals" style={{marginTop:8}}><div className="total-row"><span>Fundo de caixa</span><span>{formatMoney(data.opening_amount_cents)}</span></div><div className="total-row"><span>Dinheiro das vendas</span><span>{formatMoney(map.CASH||0)}</span></div><div className="total-row"><span>Esperado em espécie</span><strong>{formatMoney(data.expected_amount_cents)}</strong></div><div className="total-row"><span>Dinheiro contado</span><strong>{formatMoney(data.closing_amount_cents)}</strong></div><div className="total-row grand"><span>Diferença</span><span>{formatMoney(Number(data.closing_amount_cents)-Number(data.expected_amount_cents))}</span></div></div>{data.notes&&<><div className="divider"/><p><strong>Observações:</strong><br/>{data.notes}</p></>}<div className="divider"/><p style={{textAlign:"center"}}>Fechamento conferido pelo sistema do O Pub do Bairro</p></main>;
}
