import Link from "next/link";
import { Beer, PackagePlus, ShoppingCart } from "lucide-react";
import { addDraftKegAction, adjustStockAction } from "@/app/system-actions";
import { query } from "@/lib/db";
import { formatDateTime, formatQuantity } from "@/lib/format";
import { requirePermission } from "@/lib/auth";

export default async function StockPage({ searchParams }: { searchParams: Promise<{ erro?: string }> }) {
  await requirePermission("STOCK");
  const { erro } = await searchParams;
  const [products,movements,draftPools,adjustmentProducts] = await Promise.all([
    query<{ stock_pool_id:number; representative_product_id:number; name:string; category:string; stock_quantity:number|string; min_stock:number|string; sale_unit:string; unlimited:boolean; stock_kind:string|null; product_count:string }>(`SELECT sp.id AS stock_pool_id,MIN(p.id) AS representative_product_id,STRING_AGG(p.name,' + ' ORDER BY p.name) AS name,
      STRING_AGG(DISTINCT p.category,', ' ORDER BY p.category) AS category,sp.stock_quantity,sp.min_stock,sp.sale_unit,sp.unlimited,sp.stock_kind,COUNT(*)::text AS product_count
      FROM stock_pools sp JOIN products p ON p.stock_pool_id=sp.id AND p.active=TRUE AND p.deleted_at IS NULL
      GROUP BY sp.id ORDER BY (NOT sp.unlimited AND sp.stock_quantity<=sp.min_stock) DESC,MIN(p.category),MIN(p.name)`),
    query<{ id:number; product_name:string; quantity:number|string; reason:string; user_name:string; created_at:string; sale_unit:string }>(`SELECT sm.id,p.name AS product_name,sm.quantity,sm.reason,u.name AS user_name,sm.created_at,sp.sale_unit FROM stock_movements sm JOIN products p ON p.id=sm.product_id JOIN stock_pools sp ON sp.id=sm.stock_pool_id JOIN users u ON u.id=sm.user_id ORDER BY sm.created_at DESC LIMIT 30`),
    query<{id:number;name:string;stock_kind:"DRAFT_BEER"|"DRAFT_WINE";stock_quantity:number|string;min_stock:number|string}>(`SELECT id,name,stock_kind,stock_quantity,min_stock FROM stock_pools WHERE stock_kind IN ('DRAFT_BEER','DRAFT_WINE') ORDER BY stock_kind`),
    query<{id:number;name:string;category:string;active:boolean;stock_quantity:number|string;sale_unit:string;unlimited:boolean;stock_kind:string|null}>(`SELECT p.id,p.name,p.category,p.active,sp.stock_quantity,sp.sale_unit,sp.unlimited,sp.stock_kind
      FROM products p JOIN stock_pools sp ON sp.id=p.stock_pool_id
      WHERE p.deleted_at IS NULL
      ORDER BY p.active DESC,p.category,p.name`),
  ]);
  const reasons:Record<string,string>={ITEM_ADDED:"Lançamento em comanda",ITEM_REMOVED:"Item removido",MANUAL_ADJUSTMENT:"Ajuste manual",PRODUCT_EDIT:"Edição do produto",KEG_ADDED:"Galão de 50 L adicionado",SALE_CANCELLED:"Venda cancelada",COMMAND_CANCELLED:"Comanda cancelada"};
  const lowStock=products.rows.filter((product)=>!product.unlimited&&Number(product.stock_quantity)<=Number(product.min_stock));
  return <><div className="page-head"><div><p className="eyebrow">Inventário</p><h2>Controle de estoque</h2><p>A baixa acontece ao lançar na comanda e retorna quando o item é removido.</p></div><Link href="/imprimir/lista-compras" target="_blank" className="btn btn-primary"><ShoppingCart size={16}/> Lista de compras ({lowStock.length})</Link></div>{erro&&<div className="alert alert-error">{erro}</div>}
    {lowStock.length>0&&<div className="alert alert-error">{lowStock.length} produto(s) atingiram o estoque mínimo e já estão na lista de compras.</div>}
    <section className="draft-stock-section"><div className="page-head" style={{marginBottom:12}}><div><h3>Galões de chopp</h3><p>Cada galão acrescenta 50 L ao saldo escolhido.</p></div></div><div className="grid grid-2">{draftPools.rows.map((pool)=><article className="card draft-stock-card" key={pool.id}><div className="draft-stock-card-head"><Beer size={25}/><div><span>{pool.stock_kind==="DRAFT_BEER"?"CHOPP CERVEJA":"CHOPP VINHO"}</span><strong>{formatQuantity(pool.stock_quantity,"L")}</strong></div></div><form action={addDraftKegAction} className="draft-keg-form"><input type="hidden" name="stockKind" value={pool.stock_kind}/><div className="field"><label>Quantidade de galões</label><input className="input" name="kegCount" type="number" min="1" max="20" step="1" defaultValue="1" required/></div><button className="btn btn-primary" type="submit"><PackagePlus size={16}/> Adicionar galão de 50 L</button></form></article>)}</div></section>
    <section className="card" style={{marginBottom:22}}><h3>Ajuste manual</h3><p>Todos os cadastros aparecem abaixo. Para chopes, a movimentação altera o saldo compartilhado em litros.</p><form action={adjustStockAction} className="form-grid"><div className="field"><label>Produto cadastrado</label><select className="select" name="productId" required><option value="">Selecione</option>{adjustmentProducts.rows.map((product)=><option key={product.id} value={product.id} disabled={product.unlimited}>{product.name}{!product.active?" (inativo)":""} — {product.unlimited?"estoque ilimitado":`saldo ${formatQuantity(product.stock_quantity,product.sale_unit)}`}{product.stock_kind?" — compartilhado":""}</option>)}</select><small>Cadastros com estoque ilimitado são exibidos apenas para consulta.</small></div><div className="field"><label>Movimentação</label><select className="select" name="movementType" defaultValue="ENTRY" required><option value="ENTRY">Entrada de estoque</option><option value="EXIT">Saída de estoque</option></select></div><div className="field"><label>Quantidade</label><input className="input" name="quantity" type="number" min="0.001" step="0.001" placeholder="Informe somente um valor positivo" required/><small>Use a unidade exibida ao lado do saldo: un., kg ou L.</small></div><div className="form-submit-field"><button className="btn btn-primary" type="submit">Registrar movimentação</button></div></form></section>
    <div className="grid grid-2"><section><h3>Saldo dos produtos</h3><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Saldo</th><th>Mínimo</th></tr></thead><tbody>{products.rows.map(p=><tr key={p.stock_pool_id}><td><strong>{p.name}</strong>{Number(p.product_count)>1&&<><br/><span className="badge badge-blue stock-shared-badge">Compartilhado</span></>}</td><td>{p.category}</td><td><span className={`badge ${p.unlimited?"badge-blue":Number(p.stock_quantity)<=Number(p.min_stock)?"badge-red":"badge-green"}`}>{p.unlimited?"Ilimitado":formatQuantity(p.stock_quantity,p.sale_unit)}</span></td><td>{p.unlimited?"—":formatQuantity(p.min_stock,p.sale_unit)}</td></tr>)}</tbody></table></div></section>
      <section><h3>Últimas movimentações</h3><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Movimento</th><th>Motivo</th><th>Data</th></tr></thead><tbody>{movements.rows.map(m=><tr key={m.id}><td>{m.product_name}</td><td className="money" style={{color:Number(m.quantity)>0?"var(--green)":"var(--red)"}}>{Number(m.quantity)>0?"+":""}{formatQuantity(m.quantity,m.sale_unit)}</td><td>{m.reason==="MANUAL_ADJUSTMENT"?(Number(m.quantity)>0?"Entrada manual":"Saída manual"):(reasons[m.reason]||m.reason)}<br/><small>{m.user_name}</small></td><td>{formatDateTime(m.created_at)}</td></tr>)}</tbody></table></div></section></div>
  </>;
}
