import "server-only";

import { canManageCommand, hasPermission, isManagementRole, permissionKeys, type Permission, type SessionUser } from "@/lib/roles";

export type HelpTone = "rule" | "attention" | "tip" | "conclusion";
export type HelpSection = {
  title: string;
  paragraphs?: string[];
  items?: string[];
  steps?: string[];
  table?: { headers: string[]; rows: string[][] };
  callout?: { tone: HelpTone; title: string; text: string };
  checklist?: string[];
  activity?: { items: string[]; criterion: string };
  flow?: string[];
};
export type HelpChapter = { number: number; title: string; subtitle: string; audience: string; sections: HelpSection[] };

const chapters: HelpChapter[] = [
{number:1,title:"Como usar este curso",subtitle:"Orientações para aprender com segurança e usar o manual no dia a dia.",audience:"Todos os colaboradores.",sections:[
 {title:"Estrutura de cada capítulo",table:{headers:["Elemento","Como utilizar"],rows:[["Quem deve estudar","Mostra quais perfis precisam dominar o assunto."],["Passo a passo","Apresenta a sequência correta de cliques e conferências."],["Atenção / Regra","Destaca ações que afetam estoque, caixa ou histórico."],["Atividade prática","Permite comprovar que o colaborador sabe executar o processo."],["Checklist","Serve para a rotina diária e para a avaliação final."]]}},
 {title:"Regras gerais de operação",items:["Use somente o seu próprio usuário. Nunca compartilhe senha.","Leia a mensagem exibida antes de confirmar um cancelamento ou exclusão.","Confira cliente, produtos, quantidades e pagamentos antes de finalizar.","Não atualize várias vezes a página enquanto uma ação estiver sendo processada.","Quando houver dúvida financeira ou de estoque, pare e chame o Gerente ou Administrador."],callout:{tone:"attention",title:"A tela pode mudar conforme o perfil",text:"O menu mostra somente os módulos liberados para o usuário. Se uma função citada no manual não aparecer, verifique o perfil e as permissões com a gestão."}},
 {title:"Legenda utilizada",table:{headers:["Sinal","Significado"],rows:[["Verde","Situação concluída, ativa ou conferida."],["Azul","Informação, atualização automática ou processo em andamento."],["Amarelo","Atenção ou item aguardando ação."],["Vermelho","Erro, estoque baixo, cancelamento ou ação crítica."]]}},
 {title:"Atividade 1 - localização",activity:{items:["Localize o sumário digital.","Encontre o capítulo correspondente ao seu perfil.","Abra três assuntos diferentes."],criterion:"O colaborador localiza três assuntos sem ajuda."}}
]},
{number:2,title:"Acesso, navegação e segurança",subtitle:"Entrada, saída, menu lateral, mensagens e cuidados com a conta.",audience:"Todos os colaboradores.",sections:[
 {title:"Entrar no sistema",steps:["Abra o sistema — utilize o endereço disponibilizado pela gestão no navegador do computador ou dispositivo autorizado.","Informe usuário e senha — digite o usuário cadastrado e a senha inicial ou atual.","Clique em Acessar sistema — após a validação, o sistema abre a primeira área permitida para o seu perfil.","Confira sua identificação — na parte inferior do menu aparecem seu nome e o perfil ativo."],callout:{tone:"rule",title:"Senha pessoal",text:"A senha deve ter pelo menos 8 caracteres. Em Configurações, qualquer usuário pode alterar somente a própria senha."}},
 {title:"Menu lateral",paragraphs:["O menu é organizado em Operação, Cadastros, Estoque, Financeiro, Gestão e Conta. Em telas menores, use o botão de menu para abrir a barra lateral. A barra pode ser rolada para alcançar as opções mais abaixo."]},
 {title:"Mensagens e pop-ups",items:["Mensagens verdes confirmam que a ação foi concluída.","Mensagens vermelhas informam o que precisa ser corrigido.","Pop-ups são abertos no centro da tela. Leia todo o conteúdo antes de confirmar.","Use Fechar, Voltar ou o X para sair sem executar a ação."]},
 {title:"Sair do sistema",paragraphs:["No fim do turno, clique em Sair, na parte inferior da barra lateral. Não feche apenas a janela se o computador for compartilhado."],callout:{tone:"attention",title:"Acesso negado",text:"Se o sistema informar que o perfil não possui acesso, não tente contornar a restrição. Solicite a revisão da permissão ao Gerente ou Administrador."}},
 {title:"Atividade 2 - acesso seguro",activity:{items:["Entrar com o usuário de treinamento.","Abrir e fechar o menu lateral.","Acessar Configurações e identificar a área de alteração de senha.","Sair corretamente."],criterion:"O colaborador conclui a sequência sem compartilhar credenciais."}}
]},
{number:3,title:"Perfis de usuário e permissões",subtitle:"Separação de responsabilidades e trilhas de aprendizagem por função.",audience:"Todos os colaboradores e responsáveis por cadastro de usuários.",sections:[
 {title:"Perfis padrão",table:{headers:["Perfil","Acesso padrão","Responsabilidade principal"],rows:[["Administrador","Todos os módulos","Controle completo, usuários, permissões e gestão."],["Gerente","Todos os módulos","Operação e gestão. Não administra outros Gerentes ou Administradores."],["Caixa","Visão geral, Comandas, Venda rápida, Pendências, Delivery e Clientes","Finalizar vendas e atender o balcão. A abertura do caixa depende da gestão."],["Garçom","Visão geral e Comandas","Abrir comandas, lançar produtos, organizar mesas e enviar à cozinha."],["Atendente","Visão geral e Comandas","Atendimento de salão com as mesmas limitações operacionais do Garçom."],["Cozinha","Visão geral e Cozinha","Atualizar o preparo dos itens enviados."]]},callout:{tone:"tip",title:"Permissões personalizadas",text:"O Administrador ou Gerente pode liberar ou retirar módulos. Áreas de gestão continuam restritas aos perfis Administrador e Gerente."}},
 {title:"Limites importantes",items:["Somente Caixa, Gerente e Administrador podem remover itens já lançados, fechar ou cancelar comandas.","Somente Gerente e Administrador acessam Caixa, Financeiro, Funcionários, Pagamentos pendentes, Manutenção, Relatórios, Agenda e Histórico.","Administrador sempre possui acesso completo.","Gerente pode cadastrar somente Caixa, Cozinha, Garçom e Atendente."]},
 {title:"Trilha por perfil",table:{headers:["Perfil","Capítulos obrigatórios"],rows:[["Administrador","1 a 26"],["Gerente","1 a 26, com atenção aos capítulos 17 a 22"],["Caixa","1 a 11, 13, 14, 23, 24 e 25"],["Garçom / Atendente","1 a 8, 12, 23, 24 e 25"],["Cozinha","1 a 5, 11, 12, 24 e 25"]]},callout:{tone:"rule",title:"Usuário do sistema não é cadastro de funcionário",text:"O usuário serve para entrar no sistema. O cadastro na aba Funcionários serve para vincular Vale funcionário. Uma mesma pessoa pode precisar dos dois cadastros."}}
]},
{number:4,title:"Rotina de abertura do dia",subtitle:"Preparação do sistema antes do primeiro atendimento.",audience:"Administrador e Gerente. Caixa, Garçom, Atendente e Cozinha devem conhecer a conferência.",sections:[
 {title:"Sequência recomendada",flow:["Entrar","Conferir equipe","Ver estoque","Abrir caixa","Iniciar atendimento"],steps:["Verifique usuários e mesas — em Configurações, confirme que os colaboradores e as mesas do dia estão ativos.","Confira produtos e estoque — observe alertas de estoque baixo e confira os saldos críticos antes da abertura.","Abra o Caixa diário — informe somente o fundo físico inicial disponível na gaveta.","Confira Venda rápida — a tela deve indicar Caixa aberto. Se houver pendências antigas, revise-as antes de iniciar uma nova venda.","Confira Cozinha e Delivery — as telas não devem apresentar pedidos antigos indevidamente ativos."],callout:{tone:"attention",title:"Um caixa por vez",text:"O sistema permite somente um caixa aberto. Se aparecer a mensagem de que já existe caixa, consulte a tela Caixa antes de tentar novamente."}},
 {title:"Checklist de abertura",checklist:["Usuários do turno ativos.","Mesas do salão conferidas.","Produtos principais disponíveis.","Estoque baixo revisado.","Fundo de caixa contado e registrado.","Impressora e papel conferidos.","Cozinha e Delivery sem pendências indevidas."]}
]},
{number:5,title:"Visão geral",subtitle:"Leitura do painel que acompanha a operação em tempo real.",audience:"Todos os perfis com acesso à Visão geral.",sections:[
 {title:"O que aparece no painel",table:{headers:["Indicador","Interpretação"],rows:[["Comandas abertas","Atendimentos de salão em andamento."],["Deliveries ativos","Pedidos de retirada em preparo ou prontos."],["Total previsto","Vendas do caixa aberto somadas às comandas abertas. Aparece somente a quem possui acesso Financeiro."],["Em preparo","Quantidade de itens da Cozinha aguardando, preparando ou prontos."],["Estoque baixo","Saldos que atingiram o mínimo ou ficaram abaixo."]]}},
 {title:"Atendimentos em andamento",paragraphs:["A tela mostra todas as comandas abertas e também as vendas rápidas de Delivery ativas. Os cards de Delivery são identificados pelo ícone de moto. A atualização é automática."],items:["Clique na comanda para abrir o atendimento, quando seu perfil tiver acesso.","Clique no card de Delivery para ir à tela de retirada, quando permitido.","Comandas prioritárias ficam destacadas e exibem o motivo registrado."],callout:{tone:"tip",title:"Use o painel como radar",text:"A Visão geral é ideal para acompanhar atrasos, entregas ativas, estoque baixo e volume de atendimento sem abrir cada módulo."}},
 {title:"Atividade 3 - leitura operacional",activity:{items:["Identificar quantas comandas estão abertas.","Localizar um delivery pelo ícone de moto.","Explicar o significado de Em preparo e Estoque baixo."],criterion:"O colaborador interpreta os indicadores sem confundir venda concluída com atendimento aberto."}}
]},
{number:6,title:"Comandas - abertura e identificação",subtitle:"Criação correta de um atendimento de salão.",audience:"Garçom, Atendente, Caixa, Gerente e Administrador.",sections:[
 {title:"Abrir nova comanda",steps:["Abra Comandas — na parte superior, localize o formulário Abrir nova comanda.","Identifique a comanda — informe número, nome ou ambos. Um deles é obrigatório. O nome pode ter até 80 caracteres.","Informe o cliente — o nome é opcional e serve para reconhecer o atendimento. Também é possível adicionar observação.","Selecione as mesas — marque uma ou várias mesas. A mesma mesa pode estar vinculada a outras comandas abertas.","Clique em Abrir comanda — o sistema abre imediatamente a tela de produtos e opções da comanda."],callout:{tone:"attention",title:"Identificação não pode repetir",text:"Um número ou nome já usado por outra comanda aberta não pode ser reutilizado. Escolha outro identificador ou localize a comanda existente."}},
 {title:"Padrão recomendado de nomes",table:{headers:["Situação","Exemplo recomendado"],rows:[["Comanda numerada","Número 24"],["Reserva ou aniversário","Aniversário da Maria"],["Grupo sem número","Empresa Alfa - mesa externa"],["Número e nome","Número 18 + João"]]}},
 {title:"Cards de comandas abertas",paragraphs:["Cada card mostra o nome da comanda em negrito, número, cliente, mesas, quantidade de itens, horário e total. As comandas prioritárias aparecem primeiro."]},
 {title:"Atividade 4 - abrir comanda",activity:{items:["Abrir uma comanda de treinamento com nome e número.","Selecionar duas mesas.","Conferir o card criado na lista e na Visão geral."],criterion:"O identificador, as mesas e o cliente aparecem corretamente."}}
]},
{number:7,title:"Comandas - produtos, mesas e cozinha",subtitle:"Lançamento, controle de estoque, organização de mesas e envio para preparo.",audience:"Garçom, Atendente, Caixa, Gerente e Administrador. Cozinha deve conhecer o fluxo de recebimento.",sections:[
 {title:"Adicionar produtos",steps:["Pesquise — digite parte do nome ou da categoria. O resultado é filtrado imediatamente.","Confira disponibilidade — o card mostra preço, categoria e quantidade disponível. Produtos sem estoque ficam bloqueados.","Informe a quantidade — use um número inteiro dentro do saldo disponível.","Clique em Adicionar — o item entra na comanda e o estoque é baixado imediatamente."],callout:{tone:"rule",title:"Baixa imediata",text:"O estoque é movimentado no momento em que o item é lançado, não no fechamento. Se um item for removido por Caixa ou gestão, o saldo retorna."}},
 {title:"Mesas e prioridade",items:["Abra Mesas desta comanda para trocar, adicionar ou retirar mesas, mantendo ao menos uma selecionada.","Use Prioridade somente quando houver um motivo real e descreva a situação.","Atualize ou remova a prioridade quando o motivo deixar de existir."]},
 {title:"Enviar itens para a cozinha",paragraphs:["Somente produtos cadastrados no setor Cozinha geram preparo. Quando houver item novo, escolha o formato do pedido e clique em Enviar itens para a cozinha. O pedido de produção será aberto para impressão."],table:{headers:["Status","Significado"],rows:[["Novo","Item lançado, ainda não enviado à Cozinha."],["Enviado","Aguardando início do preparo."],["Preparando","A Cozinha iniciou a produção."],["Pronto","Item finalizado."],["Entregue","Item entregue ao salão. Em Delivery, a entrega depende da confirmação do código."]]},callout:{tone:"attention",title:"Remoção restrita",text:"Garçom e Atendente não removem itens já lançados. A correção deve ser solicitada ao Caixa, Gerente ou Administrador."}},
 {title:"Atividade 5 - fluxo da comanda",activity:{items:["Adicionar um item de entrega direta e um item de Cozinha.","Alterar as mesas.","Marcar e remover prioridade.","Enviar o item da Cozinha e escolher um formato de impressão."],criterion:"O estoque é baixado e somente o item correto aparece na Cozinha."}}
]},
{number:8,title:"Fechamento, clientes e pagamentos",subtitle:"Identificação do cliente, desconto, taxa, divisão e formas de pagamento.",audience:"Caixa, Gerente e Administrador. Garçom e Atendente devem conhecer o encaminhamento ao Caixa.",sections:[
 {title:"Antes de fechar",checklist:["Todos os produtos e quantidades conferidos.","Nenhum item lançado em duplicidade.","Itens da cozinha enviados quando necessário.","Desconto autorizado e corretamente informado.","Taxa de serviço revisada.","Cliente e pagamentos confirmados."]},
 {title:"Identificação do cliente",paragraphs:["A identificação é opcional. Pesquise por nome ou CPF e selecione um cadastro. Se não houver cadastro, use Cadastrar novo e informe Nome, CPF e Contato. Para finalizar sem identificação, deixe a busca vazia."],callout:{tone:"tip",title:"Nome avulso",text:"Na Venda rápida, é possível digitar somente o nome e usá-lo na notinha sem criar cadastro. No fechamento de comanda, selecione um cadastro, crie um novo ou deixe sem identificação."}},
 {title:"Formas de pagamento",table:{headers:["Forma","Uso correto"],rows:[["Dinheiro","Pagamento físico em espécie."],["PIX","Pagamento confirmado na conta do estabelecimento."],["Cartão de débito","Transação aprovada no débito."],["Cartão de crédito","Transação aprovada no crédito."],["Vale funcionário","Exige funcionário ativo e cria uma pendência para quitação."],["Crédito em loja","Exige cliente cadastrado e saldo disponível."]]}},
 {title:"Normal, divisão por pessoas e pagamento misto",items:["Normal: uma forma paga o total.","Divisão por pessoas: informe de 1 a 50 pessoas e registre como cada parte foi paga.","Pagamento misto: combine até 10 lançamentos, por exemplo PIX + crédito + dinheiro.","Use Usar saldo restante para preencher o valor que falta.","A soma informada deve ser exatamente igual ao total da venda."],callout:{tone:"attention",title:"Crédito em loja",text:"Selecione o cliente dono do crédito. Se o saldo não cobrir o total, informe quanto será usado e escolha outra forma para o restante."}},
 {title:"Finalização",paragraphs:["Quando o indicador mostrar Pagamento completo, escolha o formato da notinha: térmica 80 mm, térmica 58 mm ou A4. Clique em Finalizar e abrir notinha."],callout:{tone:"rule",title:"Não feche duas vezes",text:"Após clicar em Finalizar, aguarde a notinha abrir. Repetir o clique ou voltar durante o processamento pode gerar dúvida operacional."}},
 {title:"Atividade 6 - pagamentos",activity:{items:["Simular um pagamento normal.","Simular divisão entre três pessoas.","Simular PIX + cartão de crédito.","Simular uso parcial de crédito em loja.","Identificar um Vale funcionário."],criterion:"Em cada cenário, o saldo restante chega a zero e as referências obrigatórias são selecionadas."}}
]},
{number:9,title:"Venda rápida",subtitle:"Venda de balcão completa, sem abrir uma comanda manualmente.",audience:"Caixa, Gerente e Administrador, ou usuários com permissão Venda rápida.",sections:[
 {title:"Quando usar",paragraphs:["Use a Venda rápida quando o cliente chega ao caixa, escolhe os itens e paga imediatamente. O processo inclui carrinho, cliente, balcão ou Delivery, desconto, taxa, formas de pagamento e notinha."],callout:{tone:"attention",title:"Caixa precisa estar aberto",text:"Se a tela mostrar Caixa fechado, um Gerente ou Administrador deve abrir o caixa antes de adicionar e finalizar vendas."}},
 {title:"Passo a passo",steps:["Pesquise e adicione — use nome ou categoria. Clique em Adicionar; o botão passa a mostrar a quantidade no carrinho.","Ajuste o carrinho — use +, -, o campo de quantidade ou a lixeira. Confira o subtotal.","Identifique o cliente — deixe vazio, selecione cadastro, crie cadastro ou digite um nome avulso para a notinha.","Escolha o atendimento — use Balcão ou Retirada por aplicativo.","Informe o pagamento — use as mesmas regras do fechamento de comanda.","Escolha a notinha e finalize — para Delivery, o sistema também gera o código de retirada de 4 dígitos."]},
 {title:"Salvamento automático",paragraphs:["Ao adicionar o primeiro produto, o sistema cria uma pendência numerada. Produtos, quantidades, cliente, atendimento e pagamento são salvos a cada alteração. O indicador mostra se o pedido está atualizando, salvo ou apenas armazenado no dispositivo."],table:{headers:["Indicador","O que fazer"],rows:[["Atualizando pedido pendente","Aguarde alguns segundos."],["Salvo nas Pendências","A venda pode ser retomada pela aba Pendências de venda."],["Salvo neste dispositivo","A internet está ausente ou instável. Não limpe os dados do navegador; aguarde a reconexão."]]},callout:{tone:"tip",title:"Salvar e deixar pendente",text:"Use o botão com ícone de disquete quando quiser sair da venda e deixá-la claramente na lista de Pendências de venda."}},
 {title:"Atividade 7 - venda rápida",activity:{items:["Adicionar dois produtos.","Alterar quantidades.","Digitar um nome avulso.","Configurar pagamento misto.","Usar Salvar e deixar pendente."],criterion:"O pedido aparece numerado em Pendências com todos os dados preservados."}}
]},
{number:10,title:"Pendências de venda",subtitle:"Consulta, retomada e descarte seguro de rascunhos da Venda rápida.",audience:"Caixa, Gerente e Administrador, ou usuários com permissão Pendências de venda.",sections:[
 {title:"Informações da lista",items:["Número do pedido pendente.","Balcão ou Retirada por aplicativo.","Resumo dos itens e subtotal atual.","Cliente cadastrado, nome avulso ou cadastro pendente.","Forma de pagamento ou divisão configurada.","Data, hora e usuário da última atualização."]},
 {title:"Retomar",steps:["Localize o pedido — use número, cliente, itens e horário para evitar abrir a pendência errada.","Clique no número ou em Continuar — a Venda rápida é reaberta com carrinho e pagamento no estado salvo.","Revise o estoque e os dados — produtos podem ter mudado desde o salvamento. Confira disponibilidade, preço, cliente e pagamento.","Continue ou finalize — as novas alterações também são salvas automaticamente."]},
 {title:"Descartar",paragraphs:["Use Descartar somente quando o pedido realmente não será concluído. Leia o pop-up centralizado e confirme o número do pedido antes de continuar."],callout:{tone:"rule",title:"Não descarte para corrigir",text:"Se a venda ainda será atendida, abra a pendência e corrija os itens. Descartar remove o rascunho da lista."}},
 {title:"Atividade 8 - recuperar pedido",activity:{items:["Abrir a pendência criada no exercício anterior.","Conferir cliente, itens e pagamentos.","Fazer uma alteração e retornar à lista."],criterion:"A alteração aparece na última atualização da mesma pendência."}}
]},
{number:11,title:"Delivery e retirada por aplicativo",subtitle:"Criação, preparo e liberação segura de pedidos retirados por motoboy do cliente.",audience:"Caixa, Delivery, Cozinha, Gerente e Administrador.",sections:[
 {title:"Fluxo completo",flow:["Venda rápida","Gerar 4 dígitos","Preparar","Conferir códigos","Liberar"]},
 {title:"Criar a retirada",steps:["Inicie pela Venda rápida — na aba Delivery, Nova retirada abre uma nova Venda rápida já configurada para Retirada por aplicativo.","Monte e pague o pedido — adicione itens, identifique o cliente se desejar e finalize o pagamento.","Código do aplicativo — se o cliente já informou o código que deverá ser passado ao motoboy, registre-o. Caso contrário, deixe em branco para resolver na aba Delivery.","Finalize — o sistema gera um código interno de retirada com 4 dígitos. Informe esse código ao cliente."],callout:{tone:"rule",title:"Dois códigos, finalidades diferentes",text:"O código de retirada de 4 dígitos é gerado pelo sistema e deve ser conferido com o motoboy. O código do aplicativo vem do cliente e pode existir ou não."}},
 {title:"Tela Delivery",table:{headers:["Situação","Ação esperada"],rows:[["Em preparo","Acompanhar os itens. Ainda não liberar."],["Pronto para retirada","Resolver o código do aplicativo e confirmar os 4 dígitos."],["Código do aplicativo pendente","Salvar o código recebido ou clicar em Marcar sem código."],["Retirado","Pedido concluído e mantido no histórico recente."],["Cancelado","Venda cancelada pela Manutenção de movimentos."]]}},
 {title:"Liberar para o motoboy",steps:["Confirme que está Pronto — todos os itens da Cozinha devem estar prontos. Pedidos sem preparo de Cozinha seguem o status definido pelo fluxo.","Resolva o código do aplicativo — salve o código informado ou confirme Marcar sem código.","Peça os 4 dígitos — o motoboy deve informar o código que o cliente recebeu.","Digite e confirme — clique em Confirmar e liberar. Somente o código correto conclui a retirada."],callout:{tone:"attention",title:"Tentativas incorretas",text:"O sistema registra falhas. Após tentativas incorretas recentes, a confirmação pode ficar bloqueada por 5 minutos. Não entregue o pedido sem a validação correta."}},
 {title:"Histórico recente",paragraphs:["A parte inferior mostra pedidos retirados e cancelados dos últimos 7 dias, com venda, cliente, código do aplicativo, data e operador."]},
 {title:"Atividade 9 - simulação de retirada",activity:{items:["Criar uma retirada de treinamento.","Localizar o código de 4 dígitos.","Marcar Sem código do aplicativo.","Atualizar um item da Cozinha até Pronto.","Confirmar a retirada com o código correto."],criterion:"O pedido muda para Retirado e aparece no histórico recente."}}
]},
{number:12,title:"Cozinha",subtitle:"Controle visual dos itens que exigem preparo.",audience:"Perfil Cozinha. Garçom, Atendente, Caixa e gestão devem conhecer o fluxo.",sections:[
 {title:"Colunas de produção",table:{headers:["Coluna","Ação"],rows:[["Aguardando","Clique em Iniciar preparo ao assumir o item."],["Em preparo","Clique em Marcar como pronto quando finalizar."],["Prontos","Em comanda normal, marque como entregue. Em Delivery, aguarde a confirmação na aba Delivery."]]}},
 {title:"Leitura do card",items:["Quantidade e nome do produto.","Comanda, mesa ou número do Delivery.","Horário em que o item foi enviado.","Destaque de prioridade e respectiva observação."],callout:{tone:"rule",title:"Delivery não é entregue pela Cozinha",text:"Quando um item de Delivery estiver pronto, ele fica aguardando a confirmação do código. A entrega final é registrada na aba Delivery."}},
 {title:"Atualização automática",callout:{tone:"tip",title:"Confira antes de clicar",text:"A tela se atualiza sozinha. Antes de clicar, confirme o nome do produto e a referência do pedido."}},
 {title:"Atividade 10 - produção",activity:{items:["Localizar um item de treinamento.","Mover de Aguardando para Em preparo.","Mover para Pronto.","Explicar por que um Delivery não pode ser marcado como entregue pela Cozinha."],criterion:"Os status mudam na ordem correta e o pedido de Delivery fica protegido."}}
]},
{number:13,title:"Clientes e crédito em loja",subtitle:"Cadastro de clientes, créditos futuros e consulta das movimentações.",audience:"Caixa, Gerente, Administrador ou usuários com permissão Clientes.",sections:[
 {title:"Cadastrar cliente",steps:["Informe o Nome — utilize o nome que permitirá localizar o cliente posteriormente.","Informe o CPF — são obrigatórios 11 números e não pode haver outro cadastro com o mesmo CPF.","Informe o Contato — telefone ou WhatsApp com pelo menos 5 caracteres.","Cadastre — o cliente passa a aparecer nas buscas de fechamento e Venda rápida."]},
 {title:"Gerar crédito em loja",paragraphs:["Na linha do cliente, informe o valor e um motivo claro, por exemplo troco não entregue ou crédito autorizado. Clique em Adicionar. O saldo passa a ficar disponível em uma compra futura."],callout:{tone:"attention",title:"Crédito representa valor",text:"Não gere crédito sem autorização. Toda concessão, utilização, devolução e ajuste fica registrada com data e responsável."}},
 {title:"Uso e devolução",items:["Para usar, selecione o cliente na venda e escolha Crédito em loja.","O valor utilizado é descontado do saldo.","Se a venda for cancelada, o valor utilizado retorna automaticamente ao cliente.","Na manutenção de pagamentos, créditos antigos são devolvidos antes da nova composição ser validada."]},
 {title:"Atividade 11 - cliente e crédito",activity:{items:["Cadastrar cliente de treinamento.","Adicionar um crédito autorizado.","Localizar o movimento gerado.","Selecionar o cliente em uma venda de treinamento."],criterion:"CPF, contato e saldo aparecem corretamente e a movimentação possui responsável."}}
]},
{number:14,title:"Funcionários e vale funcionário",subtitle:"Cadastro separado para vales e baixa de pagamentos pendentes.",audience:"Administrador e Gerente. Caixa deve saber selecionar o funcionário correto na venda.",sections:[
 {title:"Cadastrar funcionário para vale",paragraphs:["Na aba Funcionários, o nome é obrigatório. CPF, contato e cargo são opcionais. Funcionários ativos aparecem na escolha de Vale funcionário."],callout:{tone:"rule",title:"Cadastro separado",text:"Criar um usuário para login não cria automaticamente o cadastro de vale. Confira se a pessoa aparece na aba Funcionários."}},
 {title:"Gerar um vale",steps:["Escolha Vale funcionário — na forma de pagamento normal, dividida ou mista.","Selecione o funcionário — confirme o nome e, quando disponível, o cargo.","Finalize a venda — o pagamento passa a constar em Pagamentos pendentes."]},
 {title:"Quitar vale",paragraphs:["Em Pagamentos pendentes, escolha Pago pelo funcionário ou Descontado do pagamento, acrescente observação se necessário e clique em Marcar como quitado."],callout:{tone:"attention",title:"Vale quitado bloqueia cancelamento",text:"Uma venda com Vale funcionário já quitado não pode ser alterada ou cancelada na Manutenção de movimentos. Essa proteção preserva a baixa financeira."}},
 {title:"Inativar funcionário",paragraphs:["A inativação remove a pessoa das novas seleções, mas mantém vales, vendas e histórico já registrados."]},
 {title:"Atividade 12 - vale",activity:{items:["Cadastrar funcionário de treinamento.","Vincular um vale em uma venda controlada.","Localizar a pendência.","Explicar as duas formas de quitação."],criterion:"A pendência mostra venda, funcionário, valor e data corretos."}}
]},
{number:15,title:"Produtos e preços",subtitle:"Cadastro do cardápio, custos, imagens, setor e forma de controle do estoque.",audience:"Administrador, Gerente ou usuários com permissão Produtos.",sections:[
 {title:"Campos do produto",table:{headers:["Campo","Orientação"],rows:[["Nome","Salvo automaticamente em caixa alta."],["Categoria","Bebidas, chopes, drinks, porções, lanches, sobremesas ou outros."],["Preço de venda","Valor cobrado do cliente."],["Custo por unidade","Custo da unidade vendida, utilizado nos cálculos financeiros."],["Setor","Entrega direta, Bar ou Cozinha. Somente Cozinha gera pedido de preparo."],["Foto","JPG, PNG ou WebP com até 3 MB."]]}},
 {title:"Modos de estoque",table:{headers:["Modo","Uso"],rows:[["Estoque próprio","Saldo exclusivo em unidade, kg, litro, porção, dose, garrafa ou lata."],["Chopp Pilsen","Compartilha o saldo em litros do barril de referência de 50 L. Cada venda baixa 190, 300 ou 500 ml."],["Chopp Vinho","Compartilha o saldo em litros do barril de referência de 30 L. Cada venda baixa 190, 300 ou 500 ml."],["Ilimitado","Produto sem saldo e sem estoque mínimo."]]},callout:{tone:"attention",title:"Custo não pode ficar esquecido",text:"Produtos com custo zero reduzem artificialmente o custo dos itens vendidos, o valor do estoque e os relatórios de lucro."}},
 {title:"Editar, inativar ou excluir",items:["Editar permite atualizar nome, categoria, valores, setor, estoque, foto e situação.","Inativar remove o produto das novas vendas sem apagar o cadastro.","Excluir é restrito à gestão e retira o cadastro das telas; o histórico antigo é preservado."]},
 {title:"Atividade 13 - produto",activity:{items:["Cadastrar produto de treinamento com custo e preço.","Definir setor correto.","Configurar estoque próprio e mínimo.","Editar a foto ou situação.","Explicar quando usar estoque ilimitado."],criterion:"O produto aparece na busca de venda e o controle de estoque corresponde ao cadastro."}}
]},
{number:16,title:"Estoque e lista de compras",subtitle:"Consulta de saldos, entradas, saídas, chopp compartilhado e lista de compras.",audience:"Administrador, Gerente ou usuários com permissão Estoque.",sections:[
 {title:"Como o saldo se movimenta",table:{headers:["Evento","Efeito"],rows:[["Produto lançado","Saída automática do estoque."],["Item removido","Retorno automático do saldo."],["Comanda cancelada","Retorno dos itens ainda vinculados à comanda."],["Venda cancelada","Retorno dos itens da venda; histórico de itens permanece visível."],["Ajuste manual","Entrada ou saída informada pelo usuário."]]}},
 {title:"Ajuste manual",steps:["Selecione o produto — cadastros ativos e inativos aparecem. Estoques ilimitados são apenas consulta.","Escolha Entrada ou Saída — Entrada aumenta; Saída reduz.","Informe quantidade positiva — use a unidade exibida no saldo: un., kg ou L.","Registre — a movimentação fica no histórico com data e responsável."],callout:{tone:"rule",title:"Nunca use número negativo",text:"O campo de quantidade recebe somente valor positivo. A direção é definida por Entrada de estoque ou Saída de estoque."}},
 {title:"Chopp compartilhado",paragraphs:["Os cartões mostram os saldos em litros do Chopp Pilsen e Chopp Vinho. Entradas e saídas são registradas no ajuste manual em litros. Os diferentes copos vinculados consomem esse mesmo saldo."]},
 {title:"Lista de compras",paragraphs:["Produtos no mínimo ou abaixo entram na Lista de compras. Use o botão no topo para abrir a impressão e revisar quantidades necessárias."]},
 {title:"Atividade 14 - estoque",activity:{items:["Registrar entrada de treinamento.","Registrar saída controlada.","Localizar as duas movimentações.","Identificar um item no estoque mínimo.","Abrir a Lista de compras."],criterion:"Saldo e histórico refletem corretamente cada movimento."}}
]},
{number:17,title:"Caixa diário",subtitle:"Abertura, acompanhamento, conferência e fechamento do caixa diário.",audience:"Administrador e Gerente. Caixa deve conhecer os indicadores, embora a área seja de gestão.",sections:[
 {title:"Abrir o caixa",paragraphs:["Informe o fundo de caixa em espécie, ou seja, o dinheiro físico inicial da gaveta. Esse valor não é venda. Clique em Abrir caixa do dia."]},
 {title:"Acompanhar",items:["Fundo de caixa separado do faturamento.","Total vendido e vendas recentes.","Totais em Dinheiro, PIX, Débito, Crédito, Vale funcionário e Crédito em loja."]},
 {title:"Fechar",steps:["Feche todas as comandas — o sistema bloqueia o fechamento se existir alguma comanda aberta.","Conte o dinheiro físico — informe fundo inicial + dinheiro recebido nas vendas.","Confira as demais formas — digite os totais conferidos de PIX, Débito, Crédito, Vale e Crédito em loja.","Observe os indicadores — cada campo mostra Confere ou a diferença encontrada.","Registre observações — use quando houver informação relevante para a gestão.","Escolha o formato — Térmica 80 mm, térmica 58 mm ou A4.","Feche e imprima — o sistema só conclui se vendas, pagamentos e valores conferidos coincidirem."],callout:{tone:"attention",title:"Diferença precisa ser investigada",text:"Não altere valores somente para liberar o fechamento. Revise pagamentos na Manutenção de movimentos e confirme comprovantes ou dinheiro físico."}},
 {title:"Checklist de fechamento do caixa",checklist:["Sem comandas abertas.","Vendas recentes revisadas.","Dinheiro físico contado.","PIX conferido.","Débito e crédito conferidos.","Vales e créditos em loja conferidos.","Observações registradas.","Relatório impresso e guardado conforme orientação interna."]},
 {title:"Atividade 15 - caixa",activity:{items:["Abrir caixa de treinamento com fundo definido.","Explicar a diferença entre fundo e vendas.","Preencher uma conferência simulada.","Identificar o motivo de um bloqueio."],criterion:"O colaborador não mistura fundo com faturamento e sabe que o fechamento exige igualdade exata."}}
]},
{number:18,title:"Financeiro",subtitle:"Análise de faturamento, custos, margem e valor financeiro do estoque.",audience:"Administrador e Gerente.",sections:[
 {title:"Períodos",paragraphs:["Escolha Caixa atual, Este mês ou Todo o período. Os indicadores consideram somente vendas concluídas."]},
 {title:"Indicadores",table:{headers:["Indicador","Cálculo"],rows:[["Faturamento bruto","Soma das vendas concluídas."],["Custo dos itens vendidos","Custo registrado nos produtos multiplicado pelas quantidades vendidas."],["Lucro bruto","Faturamento menos custo dos itens vendidos."],["Margem bruta","Lucro bruto dividido pelo faturamento."],["Estoque a custo","Estimativa do capital investido no saldo atual."],["Estoque a preço de venda","Valor bruto potencial do saldo atual."]]},callout:{tone:"attention",title:"Lucro bruto não é lucro líquido",text:"O painel não desconta automaticamente todas as despesas do negócio, como aluguel, folha, taxas, energia e serviços."}},
 {title:"Custos e margens por produto",paragraphs:["Ao alterar custo ou preço, a margem é recalculada. Ao alterar a margem, o preço de venda é calculado. Confira o lucro por unidade antes de salvar."],callout:{tone:"rule",title:"Margem abaixo de 100%",text:"A margem deve ser revisada com critério. Produtos sem custo cadastrado deixam os resultados abaixo do valor real."}},
 {title:"Atividade 16 - leitura financeira",activity:{items:["Comparar Caixa atual e Este mês.","Explicar faturamento, custo e lucro bruto.","Localizar um produto sem custo.","Simular alteração de margem sem salvar dados reais."],criterion:"O colaborador interpreta os números e não trata lucro bruto como resultado líquido final."}}
]},
{number:19,title:"Manutenção de movimentos",subtitle:"Correção de cliente e pagamentos, consulta de itens e cancelamento após a venda.",audience:"Administrador e Gerente.",sections:[
 {title:"Localizar a venda",paragraphs:["Filtre por data inicial, data final, número do pedido ou comanda, nome do cliente ou CPF. Clique no número do pedido para abrir o pop-up de manutenção."]},
 {title:"O que pode ser corrigido",items:["Cliente cadastrado vinculado à venda.","Formas de pagamento e seus valores.","Funcionário vinculado a Vale funcionário.","Uso de Crédito em loja para o cliente selecionado."],callout:{tone:"rule",title:"A soma não muda",text:"A composição dos pagamentos pode ser reorganizada, mas a soma precisa continuar exatamente igual ao total da venda."}},
 {title:"Bloqueios",items:["Venda cancelada fica somente para consulta.","Venda com Vale funcionário já quitado não pode ter pagamentos alterados nem ser cancelada.","Crédito em loja depende de cliente ativo e saldo suficiente."]},
 {title:"Cancelar venda",steps:["Confira a venda — revise origem, cliente, itens, pagamentos e total.","Informe o motivo — use descrição clara entre 4 e 240 caracteres.","Clique em Cancelar venda — leia o pop-up centralizado e confirme somente se tiver certeza.","Revise o resultado — o estoque retorna, créditos usados são devolvidos, vales pendentes são anulados e o movimento fica no Histórico."],callout:{tone:"conclusion",title:"Histórico preservado",text:"Mesmo após o cancelamento e a devolução ao estoque, os itens originais permanecem visíveis dentro da venda e na reimpressão da notinha."}},
 {title:"Cancelamento é uma ação de gestão",callout:{tone:"attention",title:"Não use cancelamento para trocar pagamento",text:"Para trocar uma forma de pagamento, edite o movimento e mantenha a venda concluída."}},
 {title:"Atividade 17 - manutenção",activity:{items:["Localizar uma venda pelo número.","Alterar a composição de pagamentos em ambiente controlado.","Explicar o bloqueio de vale quitado.","Descrever os efeitos de um cancelamento."],criterion:"O colaborador diferencia correção de pagamento, cancelamento e simples consulta."}}
]},
{number:20,title:"Relatórios de vendas",subtitle:"Consulta do caixa atual ou de períodos históricos sem executar alterações.",audience:"Administrador e Gerente.",sections:[
 {title:"Modos de consulta",items:["Sem datas: mostra o caixa atualmente aberto.","Com data inicial e final: consulta as vendas do período escolhido.","Voltar ao caixa atual remove o filtro de datas."]},
 {title:"Informações disponíveis",table:{headers:["Área","Conteúdo"],rows:[["Resumo","Faturamento, quantidade de vendas e média por venda."],["Formas de pagamento","Quantidade de vendas e total por forma."],["Vendas","Número, origem, data, total, operador e situação."],["Produtos vendidos","Quantidade e total por produto."]]}},
 {title:"Detalhes da venda",paragraphs:["Clique em Venda # para abrir o pop-up. Ele mostra origem, cliente, situação, itens, pagamentos, subtotal, desconto, taxa, total e informações de Delivery quando aplicável. Também permite reimprimir a notinha."],callout:{tone:"tip",title:"Relatório consulta; Manutenção corrige",text:"Use Relatórios para analisar e reimprimir. Use Manutenção de movimentos para alterar cliente, pagamentos ou cancelar."}},
 {title:"Atividade 18 - relatório",activity:{items:["Consultar o caixa atual.","Consultar um período de datas.","Abrir os detalhes de uma venda.","Localizar o resumo por forma de pagamento e os produtos vendidos."],criterion:"O colaborador encontra os dados sem procurar cancelamento ou edição nesta tela."}}
]},
{number:21,title:"Agenda e histórico de atividades",subtitle:"Programação da casa e rastreabilidade das ações realizadas no sistema.",audience:"Administrador e Gerente.",sections:[
 {title:"Agenda de eventos",steps:["Escolha o mês — use as setas do calendário.","Clique no dia ou em Cadastrar evento — o formulário abre com a data selecionada quando possível.","Preencha os dados — Nome, data, horário, duração em horas e valor a pagar.","Salve — o evento aparece no calendário com horário, duração e valor.","Edite ou exclua — clique no evento existente, faça a alteração ou use Excluir evento."]},
 {title:"Histórico de atividades",paragraphs:["O Histórico registra entradas, saídas, comandas, itens, cozinha, vendas, Delivery, cancelamentos, caixa, produtos, estoque, mesas, usuários, funcionários, permissões e agenda."],items:["Filtre por usuário para revisar a atuação de uma pessoa.","Filtre por movimentação para encontrar um tipo de ação.","A lista mostra data e hora, responsável, descrição e área afetada.","A consulta exibe até 300 registros por vez."],callout:{tone:"rule",title:"Histórico não deve ser apagado",text:"O registro de atividades é parte do controle interno. Use os filtros para investigação e treinamento, sem alterar evidências operacionais."}},
 {title:"Atividade 19 - agenda e rastreabilidade",activity:{items:["Cadastrar um evento de treinamento.","Editar o evento.","Localizar no Histórico a criação ou alteração.","Filtrar as atividades por usuário."],criterion:"O evento e a ação correspondente são localizados corretamente."}}
]},
{number:22,title:"Configurações, usuários e mesas",subtitle:"Senha pessoal, criação de usuários, permissões e organização das mesas.",audience:"Todos devem estudar a senha. Administrador e Gerente devem estudar toda a administração.",sections:[
 {title:"Alterar a própria senha",paragraphs:["Em Configurações, informe senha atual, nova senha com pelo menos 8 caracteres e confirmação. Cada usuário altera somente a própria senha."]},
 {title:"Criar usuário",steps:["Informe nome — nome completo ou forma reconhecida pela equipe.","Crie o usuário — no mínimo 3 caracteres; será usado no login.","Defina senha inicial — no mínimo 8 caracteres e troca recomendada no primeiro acesso.","Escolha o perfil — Atendente, Caixa, Garçom, Cozinha e, somente para Administrador, Gerente ou Administrador.","Cadastre e revise permissões — abra Editar para conferir os módulos liberados."]},
 {title:"Permissões",items:["Administrador possui acesso completo e permanente.","Gerente não altera outro Gerente nem Administrador.","Perfis não gerenciais não recebem módulos exclusivos de gestão.","Usuário inativo não entra no sistema e suas sessões são encerradas.","O sistema deve manter pelo menos um Administrador ativo."]},
 {title:"Mesas",paragraphs:["Cadastre número e nome exibido. Na edição, altere número, nome ou situação. Uma mesa com comanda aberta não pode ser inativada."],callout:{tone:"tip",title:"Menor acesso necessário",text:"Libere somente os módulos necessários para a função. Isso reduz erros, protege dados financeiros e facilita o treinamento."}},
 {title:"Checklist de novo usuário",checklist:["Nome e usuário conferidos.","Perfil correto selecionado.","Permissões revisadas.","Senha inicial entregue de forma segura.","Alteração de senha orientada.","Trilha do manual indicada.","Cadastro de Funcionário criado separadamente se utilizar vale."]},
 {title:"Atividade 20 - administração",activity:{items:["Criar usuário de treinamento com perfil definido.","Revisar permissões.","Inativar e reativar o usuário.","Cadastrar ou editar uma mesa controlada."],criterion:"As restrições de hierarquia e de mesa aberta são compreendidas."}}
]},
{number:23,title:"Impressões e reimpressões",subtitle:"Escolha de formato, abertura da janela e recuperação de documentos.",audience:"Todos os perfis que geram pedidos, vendas ou relatórios.",sections:[
 {title:"Formatos",table:{headers:["Formato","Uso recomendado"],rows:[["Térmica 80 mm","Impressora térmica padrão de 80 mm."],["Térmica 58 mm","Impressora térmica estreita de 58 mm."],["Folha A4","Impressora comum, conferência ou arquivo."]]}},
 {title:"O que pode ser impresso",items:["Pedido da Cozinha ao enviar novos itens.","Notinha da venda ao fechar comanda ou Venda rápida.","Relatório do fechamento de caixa.","Lista de compras do estoque baixo.","Reimpressão da notinha em Relatórios ou Delivery."],callout:{tone:"attention",title:"Janela bloqueada",text:"Se a notinha não abrir, verifique se o navegador bloqueou a nova janela. Não finalize novamente antes de confirmar no sistema se a venda foi concluída."}},
 {title:"Reimprimir venda",paragraphs:["Abra Relatórios, clique no número da venda e use Reimprimir notinha. Pedidos ativos de Delivery também exibem um botão de reimpressão."]},
 {title:"Venda cancelada",paragraphs:["A reimpressão mantém os itens originais da compra mesmo quando a venda foi cancelada e o estoque devolvido."]},
 {title:"Atividade 21 - impressão",activity:{items:["Gerar um pedido de Cozinha em formato definido.","Abrir uma notinha de treinamento.","Reimprimir pela tela Relatórios.","Identificar o formato correto para cada impressora."],criterion:"O colaborador não duplica vendas ao resolver uma falha de janela."}}
]},
{number:24,title:"Solução de problemas",subtitle:"Respostas padronizadas para erros frequentes e situações de dúvida.",audience:"Todos os colaboradores.",sections:[
 {title:"Guia rápido",table:{headers:["Situação","Verificação e ação"],rows:[["Opção não aparece no menu","Confira o perfil. Solicite revisão da permissão à gestão."],["Usuário ou senha inválidos","Revise digitação. Peça orientação; não compartilhe outra conta."],["Caixa fechado na Venda rápida","Gerente ou Administrador deve abrir o Caixa diário."],["Produto sem estoque","Confira o saldo e solicite ajuste autorizado. Não use outro produto para representar a venda."],["Item não aparece na Cozinha","Confirme se o produto está no setor Cozinha e se foi enviado."],["Pagamento não completa","Confira forma, valor, pessoa, funcionário, cliente e saldo restante."],["Crédito em loja bloqueado","Selecione cliente cadastrado e confirme saldo suficiente."],["Vale funcionário indisponível","Confirme se há funcionário ativo cadastrado na aba Funcionários."],["Pendência salva apenas no dispositivo","Mantenha a página e os dados do navegador; reconecte a internet para sincronizar."],["Código de Delivery não confere","Não entregue. Revise o pedido e aguarde se houver bloqueio temporário."],["Caixa não fecha","Feche comandas abertas e confira cada valor exatamente com o sistema."],["Notinha não abriu","Verifique bloqueio de janela e confirme nos Relatórios se a venda existe antes de repetir."]]}},
 {title:"Quando chamar a gestão",items:["Cancelamento de venda concluída.","Diferença de caixa ou pagamento.","Ajuste de estoque sem causa confirmada.","Crédito de cliente ou vale com dúvida.","Permissão, senha, usuário inativo ou suspeita de acesso indevido.","Internet instável com venda ainda não sincronizada."],callout:{tone:"rule",title:"Preserve a informação",text:"Não apague pendências, não descarte rascunhos e não cancele movimentos apenas para retirar uma mensagem de erro. Primeiro identifique a causa."}},
 {title:"Informações para relatar um problema",checklist:["Tela ou módulo onde ocorreu.","Número da comanda, venda, pendência ou Delivery.","Mensagem exibida exatamente como apareceu.","Horário aproximado.","Usuário que executou a ação.","O que já foi conferido, sem repetir operações críticas."]}
]},
{number:25,title:"Checklists, prática e certificação interna",subtitle:"Rotinas, exercícios e validação do aprendizado.",audience:"Todos os colaboradores e responsáveis pelo treinamento.",sections:[
 {title:"Checklist do colaborador no início do turno",checklist:["Entrar com o próprio usuário.","Conferir perfil exibido.","Verificar avisos na Visão geral.","Confirmar caixa aberto quando a função envolve vendas.","Revisar comandas, Pendências de venda, Delivery ou Cozinha conforme a função."]},
 {title:"Checklist do colaborador no fim do turno",checklist:["Não deixar comanda sem responsável.","Não deixar Venda rápida apenas local sem avisar a gestão.","Revisar pendências da própria função.","Comunicar diferenças ou erros não resolvidos.","Sair do sistema."]},
 {title:"Avaliação prática por perfil",table:{headers:["Perfil","Demonstrações obrigatórias"],rows:[["Garçom / Atendente","Abrir comanda, lançar itens, alterar mesas, usar prioridade e enviar à Cozinha."],["Caixa","Fechar comanda, Venda rápida, pagamento misto, cliente, crédito, vale, pendência e Delivery."],["Cozinha","Ler card, iniciar, marcar pronto e explicar o bloqueio do Delivery."],["Gerente","Abrir/fechar caixa, estoque, manutenção, relatórios, vales, usuários e permissões."],["Administrador","Todas as demonstrações, incluindo hierarquia de usuários e revisão completa dos módulos."]]}},
 {title:"Questionário de conferência",items:["Quando o estoque é baixado em uma comanda?","Quem pode fechar ou cancelar uma comanda?","Qual é a diferença entre código de retirada e código do aplicativo?","Onde corrigir um pagamento de venda concluída?","O que acontece com os itens após cancelar uma venda?","O que fazer se a notinha não abrir?","Usuário do sistema e Funcionário para vale são o mesmo cadastro?"]},
 {title:"Registro de conclusão",paragraphs:["O responsável deve preencher o registro após a leitura dos capítulos obrigatórios e a demonstração prática do perfil."],items:["Colaborador.","Perfil treinado.","Capítulos concluídos.","Data da avaliação.","Resultado: Aprovado ou Reforço necessário.","Pontos a reforçar.","Assinatura do colaborador e do responsável."],callout:{tone:"conclusion",title:"Treinamento concluído",text:"O colaborador deve continuar usando os checklists e consultar o sumário sempre que houver dúvida operacional."}}
]},
{number:26,title:"Glossário rápido",subtitle:"Definições para consulta durante o atendimento e o treinamento.",audience:"Todos os colaboradores.",sections:[
 {title:"Termos",table:{headers:["Termo","Definição"],rows:[["Comanda","Atendimento de salão identificado por número, nome ou ambos e ligado a uma ou várias mesas."],["Venda","Movimento financeiro criado quando uma comanda ou Venda rápida é finalizada."],["Venda rápida","Venda direta de balcão ou Delivery sem abertura manual de comanda."],["Pendência de venda","Rascunho numerado da Venda rápida, salvo para continuação."],["Delivery","Retirada por aplicativo em que o cliente envia o próprio motoboy."],["Código de retirada","Código interno de 4 dígitos, gerado pelo sistema e validado no balcão."],["Código do aplicativo","Código recebido do cliente para informar ao motoboy; pode ser marcado como inexistente."],["Pagamento misto","Combinação de duas ou mais formas de pagamento na mesma venda."],["Crédito em loja","Saldo de um cliente cadastrado para uso em compra futura."],["Vale funcionário","Forma de pagamento vinculada a um funcionário e mantida como pendência até a baixa."],["Fundo de caixa","Dinheiro físico inicial da gaveta, separado do faturamento."],["Manutenção de movimentos","Área de gestão para corrigir cliente e pagamentos ou cancelar venda concluída."],["Estoque compartilhado","Saldo único consumido por mais de um produto, como os tamanhos de chopp."],["Prioridade","Destaque temporário de uma comanda com motivo registrado."],["Histórico","Registro de ações com data, usuário e área afetada."]]},callout:{tone:"tip",title:"Consulta rápida",text:"Quando uma palavra da tela gerar dúvida, procure primeiro neste glossário e depois use o sumário para abrir o capítulo correspondente."}}
]}
];

const commonChapters = new Set([1, 2, 3, 4, 24, 25, 26]);

function hasAny(user: SessionUser, permissions: Permission[]) {
  return permissions.some((permission) => hasPermission(user, permission));
}

function canAccessChapter(user: SessionUser, chapterNumber: number) {
  if (commonChapters.has(chapterNumber)) return true;
  switch (chapterNumber) {
    case 5: return hasPermission(user, "DASHBOARD");
    case 6:
    case 7: return hasPermission(user, "COMMANDS");
    case 8: return hasPermission(user, "COMMANDS") && canManageCommand(user.role);
    case 9: return hasPermission(user, "QUICK_SALES");
    case 10: return hasPermission(user, "QUICK_SALE_PENDING");
    case 11: return hasAny(user, ["DELIVERY", "KITCHEN"]);
    case 12: return hasAny(user, ["KITCHEN", "COMMANDS", "DELIVERY"]);
    case 13: return hasPermission(user, "CUSTOMERS");
    case 14: return hasAny(user, ["STAFF", "PENDING_PAYMENTS", "QUICK_SALES"]);
    case 15: return hasPermission(user, "PRODUCTS");
    case 16: return hasPermission(user, "STOCK");
    case 17: return hasPermission(user, "CASH");
    case 18: return hasPermission(user, "FINANCE");
    case 19: return hasPermission(user, "MOVEMENT_MAINTENANCE");
    case 20: return hasPermission(user, "REPORTS");
    case 21: return hasAny(user, ["AGENDA", "AUDIT_LOGS"]);
    case 22: return true;
    case 23: return hasAny(user, ["COMMANDS", "QUICK_SALES", "DELIVERY", "KITCHEN", "REPORTS", "CASH", "STOCK"]);
    default: return false;
  }
}

function tailorChapter(user: SessionUser, chapter: HelpChapter): HelpChapter {
  if (chapter.number === 14 && !hasAny(user, ["STAFF", "PENDING_PAYMENTS"])) {
    return { ...chapter, audience: "Caixa ou usuário autorizado a registrar Vale funcionário na venda.", sections: chapter.sections.filter((section) => section.title === "Gerar um vale") };
  }
  if (chapter.number === 21) {
    const sections = chapter.sections.filter((section) => {
      if (section.title === "Agenda de eventos") return hasPermission(user, "AGENDA");
      if (section.title === "Histórico de atividades") return hasPermission(user, "AUDIT_LOGS");
      return hasAny(user, ["AGENDA", "AUDIT_LOGS"]);
    });
    return { ...chapter, sections };
  }
  if (chapter.number === 22 && !isManagementRole(user.role)) {
    return { ...chapter, audience: "Todos os colaboradores: alteração segura da própria senha.", sections: chapter.sections.filter((section) => section.title === "Alterar a própria senha") };
  }
  if (chapter.number === 23 && !hasPermission(user, "REPORTS")) {
    return { ...chapter, sections: chapter.sections.filter((section) => section.title !== "Reimprimir venda" && section.title !== "Venda cancelada") };
  }
  return chapter;
}

export function getHelpChaptersForUser(user: SessionUser) {
  return chapters.filter((chapter) => canAccessChapter(user, chapter.number)).map((chapter) => tailorChapter(user, chapter));
}

export function canDownloadFullHelpManual(user: SessionUser) {
  return user.role === "ADMIN" || permissionKeys.every((permission) => hasPermission(user, permission));
}
