import { settleStaffVoucherAction } from "@/app/system-actions";
import { requireRole } from "@/lib/auth";
import { query } from "@/lib/db";
import { formatDateTime, formatMoney } from "@/lib/format";
import { commandLabel } from "@/lib/command-label";

type VoucherRow={id:number;sale_id:number;amount_cents:number;staff_member_name:string;staff_position:string|null;created_at:string;command_number:number|null;command_name:string|null;table_display:string;settlement_type:string|null;settled_at:string|null;settled_by_name:string|null};

export default async function PendingPaymentsPage({searchParams}:{searchParams:Promise<{erro?:string;sucesso?:string}>}){
  await requireRole(["ADMIN","MANAGER"]);
  const params=await searchParams;
  const [pending,settled]=await Promise.all([
    query<VoucherRow>(`SELECT p.id,p.sale_id,p.amount_cents,COALESCE(sm.name,p.staff_member_name,'Funcionário não informado') AS staff_member_name,sm.position AS staff_position,p.created_at,c.command_number,c.command_name,cl.display_label AS table_display,NULL::text AS settlement_type,NULL::timestamptz AS settled_at,NULL::text AS settled_by_name FROM payments p JOIN sales s ON s.id=p.sale_id JOIN commands c ON c.id=s.command_id JOIN command_locations cl ON cl.command_id=c.id LEFT JOIN staff_members sm ON sm.id=p.staff_member_id WHERE p.method='STAFF_VOUCHER' AND p.staff_voucher_status='PENDING' AND p.voided_at IS NULL AND s.status='COMPLETED' ORDER BY p.created_at`),
    query<VoucherRow>(`SELECT p.id,p.sale_id,p.amount_cents,COALESCE(sm.name,p.staff_member_name,'Funcionário não informado') AS staff_member_name,sm.position AS staff_position,p.created_at,c.command_number,c.command_name,cl.display_label AS table_display,p.staff_voucher_settlement_type AS settlement_type,p.staff_voucher_settled_at AS settled_at,u.name AS settled_by_name FROM payments p JOIN sales s ON s.id=p.sale_id JOIN commands c ON c.id=s.command_id JOIN command_locations cl ON cl.command_id=c.id LEFT JOIN users u ON u.id=p.staff_voucher_settled_by LEFT JOIN staff_members sm ON sm.id=p.staff_member_id WHERE p.method='STAFF_VOUCHER' AND p.staff_voucher_status='SETTLED' AND p.voided_at IS NULL ORDER BY p.staff_voucher_settled_at DESC LIMIT 50`),
  ]);
  const total=pending.rows.reduce((sum,row)=>sum+Number(row.amount_cents),0);
  return <>
    <div className="page-head"><div><p className="eyebrow">Financeiro</p><h2>Pagamentos pendentes</h2><p>Vales de funcionários permanecem aqui até a confirmação do pagamento ou desconto.</p></div><div className="card stat pending-total"><span className="stat-label">Total pendente</span><strong className="stat-value">{formatMoney(total)}</strong><span className="stat-meta">{pending.rows.length} vale(s)</span></div></div>
    {params.erro&&<div className="alert alert-error">{params.erro}</div>}{params.sucesso&&<div className="alert alert-success">Vale retirado das pendências.</div>}
    <section><h3>Vales pendentes</h3>{pending.rows.length===0?<div className="card empty">Nenhum pagamento pendente.</div>:<div className="table-wrap"><table><thead><tr><th>Venda</th><th>Funcionário</th><th>Data</th><th>Valor</th><th>Baixa</th></tr></thead><tbody>{pending.rows.map((row)=><tr key={row.id}><td><strong>Venda #{row.sale_id}</strong><br/><small>Comanda {commandLabel(row)} · {row.table_display}</small></td><td><strong>{row.staff_member_name}</strong>{row.staff_position&&<><br/><small>{row.staff_position}</small></>}</td><td>{formatDateTime(row.created_at)}</td><td className="money">{formatMoney(row.amount_cents)}</td><td><form action={settleStaffVoucherAction} className="pending-settlement-form"><input type="hidden" name="paymentId" value={row.id}/><select className="select" name="settlementType" required defaultValue=""><option value="" disabled>Selecione</option><option value="PAID">Pago pelo funcionário</option><option value="PAYROLL_DISCOUNT">Descontado do pagamento</option></select><input className="input" name="note" placeholder="Observação opcional"/><button className="btn btn-primary btn-small" type="submit">Marcar como quitado</button></form></td></tr>)}</tbody></table></div>}</section>
    <section style={{marginTop:22}}><h3>Vales quitados recentemente</h3>{settled.rows.length===0?<div className="card empty">Nenhum vale quitado até agora.</div>:<div className="table-wrap"><table><thead><tr><th>Venda</th><th>Funcionário</th><th>Valor</th><th>Quitação</th></tr></thead><tbody>{settled.rows.map((row)=><tr key={row.id}><td>#{row.sale_id}</td><td>{row.staff_member_name}{row.staff_position&&<><br/><small>{row.staff_position}</small></>}</td><td className="money">{formatMoney(row.amount_cents)}</td><td>{row.settlement_type==="PAID"?"Pago pelo funcionário":"Descontado do pagamento"}<br/><small>{row.settled_at&&formatDateTime(row.settled_at)} · {row.settled_by_name}</small></td></tr>)}</tbody></table></div>}</section>
  </>;
}
