import { notFound } from "next/navigation";
import { PrintActions } from "@/components/print-actions";
import { BrandLogo } from "@/components/brand-logo";
import { requirePermission } from "@/lib/auth";
import { query } from "@/lib/db";
import { formatDateTime, formatMoney, formatQuantity } from "@/lib/format";

export const dynamic = "force-dynamic";
export default async function SalePrintPage({ params,searchParams }:{params:Promise<{id:string}>;searchParams:Promise<{formato?:string}>}){
  await requirePermission("COMMANDS"); const saleId=Number((await params).id); const format=(await searchParams).formato||"80";
  const sale=await query<{id:number;command_id:number;command_number:number;table_number:number;customer_name:string|null;subtotal_cents:number;discount_cents:number;service_fee_cents:number;total_cents:number;split_count:number;created_at:string;user_name:string}>(`SELECT s.id,c.id AS command_id,c.command_number,t.number AS table_number,c.customer_name,s.subtotal_cents,s.discount_cents,s.service_fee_cents,s.total_cents,s.split_count,s.created_at,u.name AS user_name FROM sales s JOIN commands c ON c.id=s.command_id JOIN bar_tables t ON t.id=c.table_id JOIN users u ON u.id=s.created_by WHERE s.id=$1`,[saleId]); if(!sale.rows[0])notFound(); const data=sale.rows[0];
  const [items,payments]=await Promise.all([query<{product_name:string;quantity:number|string;unit_price_cents:number;sale_unit:string}>("SELECT product_name,quantity,unit_price_cents,sale_unit FROM order_items WHERE command_id=$1 AND status<>'CANCELLED' ORDER BY id",[data.command_id]),query<{method:string;amount_cents:number;received_cents:number|null;change_cents:number}>("SELECT method,amount_cents,received_cents,change_cents FROM payments WHERE sale_id=$1 ORDER BY id",[saleId])]); const methods:Record<string,string>={CASH:"Dinheiro",PIX:"Pix",DEBIT:"Cartão de débito",CREDIT:"Cartão de crédito",STAFF_VOUCHER:"Vale funcionário"};
  return <main className={`print-page ${format==="80"?"receipt-80":format==="58"?"receipt-58":""}`}><PrintActions/><header className="print-title"><BrandLogo className="print-logo"/><h1>O Pub do Bairro</h1><strong>COMPROVANTE DA VENDA</strong></header><p style={{textAlign:"center"}}>Venda #{data.id} · {formatDateTime(data.created_at)}</p><div className="divider"/><p><strong>Comanda:</strong> #{data.command_number}<br/><strong>Mesa:</strong> {data.table_number}<br/><strong>Cliente:</strong> {data.customer_name||"Não informado"}<br/><strong>Atendente:</strong> {data.user_name}</p><div className="divider"/>
    {items.rows.map((item,index)=><div key={index} style={{marginBottom:9}}><div className="total-row"><span>{formatQuantity(item.quantity,item.sale_unit)} · {item.product_name}</span><strong>{formatMoney(Number(item.quantity)*item.unit_price_cents)}</strong></div><small>{formatMoney(item.unit_price_cents)} por {item.sale_unit==="KG"?"kg":item.sale_unit==="L"?"litro":"unidade"}</small></div>)}<div className="divider"/><div className="totals"><div className="total-row"><span>Subtotal</span><span>{formatMoney(data.subtotal_cents)}</span></div>{data.discount_cents>0&&<div className="total-row"><span>Desconto</span><span>- {formatMoney(data.discount_cents)}</span></div>}{data.service_fee_cents>0&&<div className="total-row"><span>Taxa de serviço</span><span>{formatMoney(data.service_fee_cents)}</span></div>}<div className="total-row grand"><span>Total</span><span>{formatMoney(data.total_cents)}</span></div>{data.split_count>1&&<div className="total-row"><span>Dividido entre {data.split_count} pessoas</span><strong>{formatMoney(Math.round(data.total_cents/data.split_count))} por pessoa</strong></div>}</div><div className="divider"/><strong>Pagamento</strong>{payments.rows.map((p,index)=><div className="total-row" key={index} style={{marginTop:7}}><span>{methods[p.method]}</span><span>{formatMoney(p.amount_cents)}</span></div>)}{payments.rows.some(p=>p.change_cents>0)&&<><div className="total-row"><span>Valor recebido</span><span>{formatMoney(payments.rows.find(p=>p.method==="CASH")?.received_cents||0)}</span></div><div className="total-row"><strong>Troco</strong><strong>{formatMoney(payments.rows.find(p=>p.method==="CASH")?.change_cents||0)}</strong></div></>}<div className="divider"/><p style={{textAlign:"center"}}>Obrigado pela preferência!</p></main>;
}
