import { createTableAction, createUserAction } from "@/app/system-actions";
import { query } from "@/lib/db";
import { roleLabel, type Role } from "@/lib/roles";
import { requireRole } from "@/lib/auth";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ erro?:string }> }) {
  await requireRole(["ADMIN"]);
  const {erro}=await searchParams; const [users,tables]=await Promise.all([query<{id:number;name:string;username:string;role:Role;active:boolean}>("SELECT id,name,username,role,active FROM users ORDER BY name"),query<{id:number;number:number;label:string;active:boolean}>("SELECT id,number,COALESCE(label,'Mesa '||number) AS label,active FROM bar_tables ORDER BY number")]);
  return <><div className="page-head"><div><p className="eyebrow">Administração</p><h2>Configurações</h2><p>Gerencie funcionários, permissões e mesas.</p></div></div>{erro&&<div className="alert alert-error">{erro}</div>}
    <div className="grid grid-2"><section className="card"><h3>Novo funcionário</h3><form action={createUserAction} className="form-stack"><div className="form-grid"><div className="field"><label>Nome</label><input className="input" name="name" required/></div><div className="field"><label>Usuário</label><input className="input" name="username" minLength={3} required/></div><div className="field"><label>Senha inicial</label><input className="input" name="password" type="password" minLength={8} required/></div><div className="field"><label>Perfil</label><select className="select" name="role"><option value="CASHIER">Caixa</option><option value="KITCHEN">Cozinha</option><option value="MANAGER">Gerente</option><option value="ADMIN">Administrador</option></select></div></div><button className="btn btn-primary" type="submit">Cadastrar funcionário</button></form><div className="divider"/><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th></tr></thead><tbody>{users.rows.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.username}</td><td><span className="badge badge-gray">{roleLabel[u.role]}</span></td></tr>)}</tbody></table></div></section>
      <section className="card"><h3>Nova mesa</h3><form action={createTableAction} className="form-stack"><div className="form-grid"><div className="field"><label>Número</label><input className="input" name="number" type="number" min="1" required/></div><div className="field"><label>Nome exibido</label><input className="input" name="label" placeholder="Ex.: Varanda 1"/></div></div><button className="btn btn-primary" type="submit">Cadastrar mesa</button></form><div className="divider"/><div className="table-wrap"><table><thead><tr><th>Número</th><th>Nome</th><th>Situação</th></tr></thead><tbody>{tables.rows.map(t=><tr key={t.id}><td>{t.number}</td><td>{t.label}</td><td><span className={`badge ${t.active?"badge-green":"badge-gray"}`}>{t.active?"Ativa":"Inativa"}</span></td></tr>)}</tbody></table></div></section></div>
  </>;
}
